In [5]:
#integer ecoding and embeddings
import numpy as np

docs = [
    'go india',
    'india india',
    'hip hip hurray',
    'jeetega bhai jeetega',
    'bhar mata ki jai',
]


In [6]:
from keras.preprocessing.text import Tokenizer
tokenizer = Tokenizer(oov_token='hestia')



In [7]:
tokenizer.fit_on_texts(docs)

In [9]:
tokenizer.word_index

{'hestia': 1,
 'india': 2,
 'hip': 3,
 'jeetega': 4,
 'go': 5,
 'hurray': 6,
 'bhai': 7,
 'bhar': 8,
 'mata': 9,
 'ki': 10,
 'jai': 11}

In [10]:
tokenizer.word_counts

OrderedDict([('go', 1),
             ('india', 3),
             ('hip', 2),
             ('hurray', 1),
             ('jeetega', 2),
             ('bhai', 1),
             ('bhar', 1),
             ('mata', 1),
             ('ki', 1),
             ('jai', 1)])

In [11]:
tokenizer.document_count

5

In [13]:
sequences = tokenizer.texts_to_sequences(docs)

In [14]:
sequences

[[5, 2], [2, 2], [3, 3, 6], [4, 7, 4], [8, 9, 10, 11]]

In [16]:
mat = tokenizer.texts_to_matrix(docs)

In [17]:
mat

array([[0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1.]])

In [18]:
from keras.utils import pad_sequences

In [19]:
sequences = pad_sequences(sequences=sequences) 

In [20]:
sequences

array([[ 0,  0,  5,  2],
       [ 0,  0,  2,  2],
       [ 0,  3,  3,  6],
       [ 0,  4,  7,  4],
       [ 8,  9, 10, 11]], dtype=int32)

In [24]:
sequences = pad_sequences(sequences=sequences , padding='post') 

In [25]:
sequences

array([[ 0,  0,  5,  2],
       [ 0,  0,  2,  2],
       [ 0,  3,  3,  6],
       [ 0,  4,  7,  4],
       [ 8,  9, 10, 11]], dtype=int32)